### ISSUE TITLE
ConditionValueExpression arguments aren't handled properly

### ISSUE THREAD

**Issue by thomaspatzke** [SigmaHQ/pySigma-backend-insightidr#1]
The code [at this location](https://github.com/SigmaHQ/pySigma-backend-insightidr/blob/4eea830b9e7963d762d49181def51b393bfa3484/sigma/backends/insight_idr/insight_idr.py#L190) assumes that the argument has a *field* attribute, which isn't the case for ConditionValueExpression objects (keyword search terms). This causes that a Sigma CLI run on the whole Sigma rule repository fails:

```
$ sigma convert -t insightidr -s ../sigma/rules
[...]
  File "[...]/sigma/backends/insight_idr/insight_idr.py", line 190, in <listcomp>
    fields = list(set([arg.field for arg in cond.args]))
AttributeError: 'ConditionValueExpression' object has no attribute 'field'
```

Fix: the if before must additionally check if all arguments are from the expected type. A test should be added for this case.

**Comment by thomaspatzke** [comment]
Just implemented [two tests](https://github.com/SigmaHQ/pySigma-backend-insightidr/blob/4633321a51cdf1feec3adbb68cfbb36d58fc0bb8/tests/test_backend_insight_idr.py#L106) for the issue and it appears that the same issue also applies for AND expressions [in convert_condition_and()](https://github.com/SigmaHQ/pySigma-backend-insightidr/blob/4eea830b9e7963d762d49181def51b393bfa3484/sigma/backends/insight_idr/insight_idr.py#L239).

**Comment by mbabinski** [comment]
Hey @thomaspatzke, I see what you are saying. Are keywords meant to support partial/wildcard matches? If so, I think this would fall under the concept of "loose search". Then query should be:

`"val1" OR "val2", loose`

or

`"val1" AND "val2", loose`

I will look into how to implement this at my earliest convenience!
