### ISSUE TITLE
To convert more than one rule

### ISSUE THREAD

**Issue by dogukankurnaz** [SigmaHQ/pySigma-backend-insightidr#6]
Hi everyone!

I used a glob library to convert multiple rules. In my test.py file, it imported the rules one by one into a list, but when it started to print the rules to the screen, after a certain rule:

The InsightIDR backend does not support the CurrentDirectory, IntegrityLevel, or imphash fields for process start rules.

SigmaHQ has more than +1000 proccess_Creation rules. What do you suggest me to do?

**Comment by slincoln-aiq** [comment]
Hello,

You could use a try/except when converting the rules, so if it catches an exception you can still continue on and convert the rest of the rules. For example, let say you are converting each file in your library one at a time as a `SigmaRule` (as opposed to a `SigmaCollection`), here's some basic pseudo-code to give you the idea: 

```python
my_backend = SomeBackendClass()
for my_rule_file in my_library_directory:
    sigma_rule = SigmaRule.from_yaml(my_rule_file)
    try:
        output = my_backend.convert_rule(sigma_rule)
        print(output[0])
    except Exception as exc:
        print(exc)
```

**Comment by mbabinski** [comment]
Hey @dogukankurnaz, sorry for the slow reply! In addition to @slincoln-aiq's suggestion, if you are using [sigma-cli](https://github.com/SigmaHQ/sigma-cli/tree/main), you can use the --skip-unsupported option, which will cause the conversion tool to simply ignore rules which cannot be processed by the chosen backend. For example:

`sigma convert -t insight-idr /path/to/rules -o /output/path/output_queries.txt --skip-unsupported` 

I hope this helps! Let me know if either of these work for you.

**Comment by dogukankurnaz** [comment]
Hello @mbabinski ,

I can't try right now but I felt that probably the answer you wrote would solve my problem.

I made the manual solution myself:

I wrote 2 python scripts, one of them translates all sigma rules into proper format.

The other one, if the translator fails, tells me which line it is on. I delete that sigma rule and add it to the list.

**Comment by mbabinski** [comment]
Nice work!
