### ISSUE TITLE
Increase Supported pySigma Subversion

### ISSUE THREAD

**Issue by slincoln-aiq** [SigmaHQ/pySigma-backend-insightidr#7]
Current supported version is pysigma = "^0.8.1". Would it be possible to increase the subversion to 9 (^0.9.0?) so its similar to the other currently released backends?

Thanks!

**Comment by mbabinski** [comment]
Hi @slincoln-aiq, sorry for the slow reply and thank you for the Issue. I am going to work on this and hopefully have it done this week!

Regards,
Micah Babinski
